export type Handover = {
  seq: number;
  dateTime: string;
  fromName: string;
  fromBadge: string;
  fromAgency: string;
  toName: string;
  toBadge: string;
  toUnit: string;
  place: string;
  reason: string;
  sealState: string;
  sealNumber: string;
  notes: string;
};

export type Incident = {
  id: string;
  createdAt: string;
  caseNumber: string;
  dateTime: string;
  location: string;
  borderPoint: string;
  officerName: string;
  badgeId: string;
  agency: string;
  witnessName: string;
  witnessId: string;
  deviceType: string;
  make: string;
  model: string;
  serial: string;
  imei: string;
  condition: string;
  power: "on" | "off" | "unknown";
  screenLocked: "yes" | "no" | "unknown";
  encryption: "yes" | "no" | "unknown";
  network: string;
  circumstances: string;
  photo?: string;
  handovers: Handover[];
};
