/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IncidentRouteImport } from './routes/incident'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as IndexRouteImport } from './routes/index'

const IncidentRoute = IncidentRouteImport.update({
  id: '/incident',
  path: '/incident',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decision': typeof DecisionRoute
  '/incident': typeof IncidentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decision': typeof DecisionRoute
  '/incident': typeof IncidentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decision': typeof DecisionRoute
  '/incident': typeof IncidentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decision' | '/incident'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decision' | '/incident'
  id: '__root__' | '/' | '/decision' | '/incident'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionRoute: typeof DecisionRoute
  IncidentRoute: typeof IncidentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/incident': {
      id: '/incident'
      path: '/incident'
      fullPath: '/incident'
      preLoaderRoute: typeof IncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionRoute: DecisionRoute,
  IncidentRoute: IncidentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
