/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HandbookRouteImport } from './routes/handbook'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedIncidentRouteImport } from './routes/_authenticated/incident'

const HandbookRoute = HandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncidentRoute = AuthenticatedIncidentRouteImport.update({
  id: '/incident',
  path: '/incident',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/decision': typeof DecisionRoute
  '/handbook': typeof HandbookRoute
  '/incident': typeof AuthenticatedIncidentRoute
  '/records': typeof AuthenticatedRecordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/decision': typeof DecisionRoute
  '/handbook': typeof HandbookRoute
  '/incident': typeof AuthenticatedIncidentRoute
  '/records': typeof AuthenticatedRecordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/decision': typeof DecisionRoute
  '/handbook': typeof HandbookRoute
  '/_authenticated/incident': typeof AuthenticatedIncidentRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/decision'
    | '/handbook'
    | '/incident'
    | '/records'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/decision' | '/handbook' | '/incident' | '/records'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/decision'
    | '/handbook'
    | '/_authenticated/incident'
    | '/_authenticated/records'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DecisionRoute: typeof DecisionRoute
  HandbookRoute: typeof HandbookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/handbook': {
      id: '/handbook'
      path: '/handbook'
      fullPath: '/handbook'
      preLoaderRoute: typeof HandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incident': {
      id: '/_authenticated/incident'
      path: '/incident'
      fullPath: '/incident'
      preLoaderRoute: typeof AuthenticatedIncidentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIncidentRoute: typeof AuthenticatedIncidentRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIncidentRoute: AuthenticatedIncidentRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DecisionRoute: DecisionRoute,
  HandbookRoute: HandbookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
